name: Check build

on: [ push, pull_request ]

jobs:
  build:
    name: Check build
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.4", "5.3", "5.2", "5.1", "luajit", "luajit-openresty"]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@v4
      - name: Make with Luarocks
        run: |
          luarocks make --pack-binary-rock -- luasocket-scm-3.rockspec
